{% set version = "0.6.9" %}
{% set sha256 = "32ea84fb87619ec6b90ca3f4bb9d9dd3d5ca12f6a5f2db9777bfc858d9e62464" %}    #[ppc64le]
{% set trt_tar = "TensorRT-7.2.0.13.CentOS-8.1.ppc64le-gnu.cuda-11.0.cudnn8.0.tar.gz" %} #[ppc64le]

{% set sha256 = "3d42890424e2a2a155df67aaace45d001a95f12d6781008c5dcf62ea480ea664" %}   #[x86_64]
{% set trt_tar = "TensorRT-7.2.1.6.CentOS-7.6.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz" %}  #[x86_64]

{% set trt_tar_dir =  environ.get('LOCAL_SRC_DIR', 0) %}

package:
  name: uff
  version: {{ version }}

source:
  - url: file://{{ trt_tar_dir }}/{{ trt_tar }}
    sha256: {{ sha256 }}  
    folder: tensorrt

build:
  number: 2
  string: py{{ python | replace(".", "") }}_{{ PKG_BUILDNUM }}
  
requirements:
  host:
    - python {{ python }}
    - wheel {{ wheel }}
  run:
    - python {{ python }}

about:
  home: https://developer.nvidia.com/tensorrt
  license: NVIDIA Software License
  license_family: Proprietary
  summary: The uff package contains a set of utilites to convert trained models from various frameworks to a common format.
  description: |
    The uff package contains a set of utilites to convert trained models from various frameworks to a common format.
  doc_url: https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/uff/uff.html

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
